import Head from "next/head";
import Featured from "../components/featured";
import PizzaList from "../components/pizzaList";
export default function Home() {
  return (
    <div className={``}>
      <Head>
        <title>Pitza - Best Pizza shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <PizzaList />
    </div>
  );
}
