import axios from "../helpers/axios";
import Head from "next/head";
import Featured from "../components/featured";
import PizzaList from "../components/pizzaList";
export default function Home({ products }) {
  return (
    <div className={``}>
      <Head>
        <title>Pitza - Best Pizza shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <PizzaList pizzaList={products} />
    </div>
  );
}

export const getServerSideProps = async () => {
  try {
    const { data } = await axios.get("/products");
    return {
      props: {
        products: data,
      },
    };
  } catch (error) {
    return {
      props: {
        products: [],
      },
    };
  }
};
